initial migration to kotlin multiplatform, targeting JVM
xn32/json5k pull request #3
Opened 2022-11-29 10:05 UTC by aSemy

Updates the build config to use Kotlin Multiplatform, however the only target is Kotlin JVM

Initial step for #1. 

### TODO

- [ ] Fix signing config

2022-11-29 10:21 UTC, xn32 commented
Thank you for the draft!

If you want, feel free to remove everything related to signing and publication on Maven Central for the time being. We can add it again when everything else is ready and thoroughly tested.

2022-11-29 10:23 UTC, aSemy commented
@xn32 It's ready for review then :) I'm working on the publishing config now, I can put it in another PR

2022-11-30 23:15 UTC, xn32 requested changes

2022-11-30 23:15 UTC, xn32 commented on build.gradle.kts
>  version = "0.2.1"
Let's start to prepare for version 0.3.0:
```suggestion
version = "0.3.0-SNAPSHOT"
```

2022-11-30 23:15 UTC, xn32 commented on build.gradle.kts
For the sake of simplicity, I would like to keep the build logic in this file for now:
```suggestion
repositories {
    mavenCentral()
}

```

2022-11-30 23:15 UTC, xn32 commented on build.gradle.kts
> +//    sign(publishing.publications["mavenJava"])
This should do the trick, I think:
```suggestion
    sign(publishing.publications)
```

2022-11-30 23:15 UTC, xn32 commented on settings.gradle.kts
> +}
```suggestion
```

2022-12-02 18:33 UTC, aSemy commented on build.gradle.kts
> +//    sign(publishing.publications["mavenJava"])
I'm not so confident, because the signing plugin is very buggy :) But it will be fixed in #4

2022-12-02 19:11 UTC, merged